import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


s = Service('C:/Test/chromedriver.exe')
driver = webdriver.Chrome(service=s)

# Open site
driver.get("https://qa.neapro.site/login")
driver.maximize_window()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("vitalya.lev@mail.ru")
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("12953585")
driver.find_element(By.CSS_SELECTOR, ".btn").click()
time.sleep(3)
# Fill Pasport
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(1) > .document-name").click()
driver.find_element(By.ID, "surname").clear()
time.sleep(1)
driver.find_element(By.ID, "surname").send_keys("Шангин")
time.sleep(1)
driver.find_element(By.ID, "name").clear()
time.sleep(1)
driver.find_element(By.ID, "name").send_keys("Виталий")
time.sleep(1)
driver.find_element(By.ID, "patronymic").clear()
time.sleep(1)
driver.find_element(By.ID, "patronymic").send_keys("Игоревич")
time.sleep(1)
driver.find_element(By.ID, "passportSeries").clear()
time.sleep(1)
driver.find_element(By.ID, "passportSeries").send_keys("1234")
time.sleep(1)
driver.find_element(By.ID, "passportNumber").clear()
time.sleep(1)
driver.find_element(By.ID, "passportNumber").send_keys("123456")
time.sleep(1)
driver.find_element(By.ID, "code").clear()
time.sleep(1)
driver.find_element(By.ID, "code").send_keys("123456")
time.sleep(1)
driver.find_element(By.ID, "cardId").clear()
time.sleep(1)
driver.find_element(By.ID, "cardId").send_keys("123456789012")
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, #birthday .mx-input").clear()
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, #birthday .mx-input").send_keys("01.01.1981")
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, #dateOfIssue .mx-input").clear()
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, #dateOfIssue .mx-input").send_keys("01.01.1990")
time.sleep(1)
driver.find_element(By.ID, "issued").clear()
time.sleep(1)
driver.find_element(By.ID, "issued").send_keys("ОВД")
time.sleep(1)
driver.execute_script("window.scrollTo(0, 1080)")
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, .vue-dadata__input").clear()
time.sleep(1)
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, .vue-dadata__input").send_keys("Ки")
time.sleep(1)
ActionChains(driver).move_by_offset(900, 700).click().perform()
time.sleep(1)
driver.find_element(By.ID, "phone").clear()
time.sleep(1)
driver.find_element(By.ID, "phone").send_keys("123456789012")
driver.find_element(By.CSS_SELECTOR, "By.CSS.SELECTOR, .upload-widget> input").send_keys("C:\\Doc.pdf")
driver.execute_script("window.scrollTo(0, 1080)")
time.sleep(5)
driver.find_element(By.LINK_TEXT, "By.LINK.TEXT, .fill").click()
