# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPZN53():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pZN53(self):
    self.driver.get("https://qa.neapro.site/login")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("vitalya.lev@mail.ru ")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("12953585")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".avatar_link")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".avatar_link").click()
    self.driver.find_element(By.LINK_TEXT, "Безопасность и вход").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .name").click()
    self.driver.find_element(By.NAME, "phone").send_keys("name=phone")
    self.driver.find_element(By.NAME, "phone").send_keys("1231232323")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".img > img").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(2) .name").click()
    self.driver.find_element(By.ID, "oldPassword").send_keys("129535851")
    self.driver.find_element(By.ID, "newPassword").send_keys("12953585")
    self.driver.find_element(By.ID, "confirmPassword").send_keys("12953585")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".img > img").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".scrollmenu")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".logout").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("vitalya.lev@mail.ru ")
    self.driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("129535851")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
